# W01_0221 {#第一周}

：有趣當作工作，是一件幸福的事情

- 稅捐債務法
- 稅捐稽徵法（核課、徵收、執行）
- 稅捐處罰法
- 稅捐救濟法

這學期還要放假2次，僅保留期末考（2題）

## 稅捐債務法

憲法第十九、二十三條規定
**依法課稅原則**（對行政機關的誡命，Gebote）

三個展開

1. 構成要件法定（事實到法律之間的對應適用關係，叫做涵攝）
2. 效果法定
   1. 稅額計算
   2. 繳納期間（債務履行）
3. 程序法定
   
### 依法課稅原則

**法**：制定法 + （授權的）法規命令 （~~行政規則~~）
行政規則 不能增加人民的稅捐負擔義務，行政機關也不可以透過行政規則，給予依法本不存在（法外的）的稅捐利益，“法外施恩”，也是對於依法課稅原則的抵觸

依法課稅的反面：依法（才能）免稅。
稅捐優惠應該在依法課稅原則的前提之下。

實務的最大爭議，操作困難在於，法律沒有明白的授權，但行政機關用大量的行政命令去填補、填充“制定法與法規命令之規範不足之處”



我們的法律制定密度太低，意志不清，法律本身很空洞，法規命令的制定也過於抽象。

看法律不夠，要看行政規則（雖然法位階最低，但很重要）：

1. 法令彙編
2. 稅務問答Q&A（自問自答，各地區國稅局達成共識的見解）
3. 不公佈的解釋函令
   1. 稱“**個案函**”，爲了確保在個案中法律適用沒問題，下級機關會寫公文給上級機關，請問個別法律問題的解釋，法律見解，往往沒有對外公開
   2. 上級機關（賦稅署）覺得這個是好問題，可能以“副知”的方式，讓別的國稅局也知道，變成**通案函**，讓各地的行政機關有一致的法律適用
   3. 經過一段時間，確認沒問題了，就會正式公告成爲**公告函**，進入**法令彙編**。

債權（權利本體）-> **請求權**（衍生性權利）

四種不同**請求權**類型：

【國家是債權人】

1. 稅款的給付請求
2. 責任債務（Haftungsschulden）給付請求

【國家是債務人】

3. **退給**稅款的給付請求
   - 有法律上的原因，透過法律的規定
   - 例如稅捐優惠
4. 返還稅款請求
   - 公法上的不當得利 
   - 無法律原因的不當得利返還
  
退給 vs. 返還：
構成要件不同！舉證責任不同！

退給稅款要件事實應由納稅義務人證明。


返還稅款，是基於稅捐的同一事實，要由稽徵機關負擔擧證責任：
- 納稅義務人說我只應該繳50塊！稽徵機關要舉證説明稅額應爲100塊，否則就只能徵收50塊


### 稅款給付請求

稅款給付

- 主給付：稅捐本金
- 附帶給付
    - 稅捐稽徵法49第一項，准用稅款主給付請求的規範
    - 附帶給付的内容：滯納金、利息、滯報金、怠報金及罰鍰等
    - 不利益的行政處分：滯納金、利息
    - 裁罰性的行政處分：滯報金、怠報金及罰鍰

> 第 20 條
> 
> 1. 依稅法規定逾期繳納稅捐應加徵滯納金者，每逾三日按滯納數額加徵百分之一滯納金；逾三十日仍未繳納者，移送強制執行。但因不可抗力或不可歸責於納稅義務人之事由，致不能依第二十六條、第二十六條之一規定期間申請延期或分期繳納稅捐者，得於其原因消滅後十日內，提出具體證明，向稅捐稽徵機關申請回復原狀並同時補行申請延期或分期繳納，經核准者，免予加徵滯納金。
> 2. 中華民國一百十年十一月三十日修正之本條文施行時，欠繳應納稅捐且尚未逾計徵滯納金期間者，適用修正後之規定。

1. 滯納金（稅捐稽徵法20條）
   - 怠於繳納，應繳未繳，遲延利息的類似，跟利息是互斥的
   - 前30天算滯納金，最多10%（稅捐稽徵法20條第1項第1句第1分句，前年修法的）
   - 是一種類似殆金的概念，是一種不利益，但不是處罰，不是裁罰，沒有制裁的意義
   - 納稅者權利保護法第7條第3項第2句，後半段【稅捐稽徵法修正，但是納保法沒有修正；一旦該當**租稅規避**，滯納金以15%計】
        >第 7 條（稅捐規避）
     >3. 納稅者基於獲得租稅利益，違背稅法之立法目的，濫用法律形式，以非常規交易規避租稅構成要件之該當，以達成與交易常規相當之經濟效果，為**租稅規避**。稅捐稽徵機關仍根據與實質上經濟利益相當之法律形式，成立租稅上請求權，並加徵滯納金及利息。
     >4. 前項租稅規避及第二項課徵租稅構成要件事實之認定，稅捐稽徵機關就其事實有舉證之責任。
     >7. 第三項之滯納金，按應補繳稅款**百分之十五**計算；並自該應補繳稅款原應繳納期限屆滿之次日起，至填發補繳稅款繳納通知書之日止，按補繳稅款，依各年度一月一日郵政儲金一年期定期儲金固定利率，按日加計利息，一併徵收。
   - 一般而言，滯納金和本金會一起被提起稅捐救濟程序

2. 利息
    - 有滯納金就沒有利息
    - 繳完滯納金之後才開始算利息
    - 前30天算滯納，第31天開始算利息（法定利率）
    - 納保法第7條第7項第2分句（租稅規避者）
        >7. 第三項之滯納金，按應補繳稅款**百分之十五**計算；並自該應補繳稅款原應繳納期限屆滿之次日起，至填發補繳稅款繳納通知書之日止，按補繳稅款，依各年度一月一日郵政儲金一年期定期儲金固定利率，按日加計利息，一併徵收。
3. 滯報金
    - 逾越期間之申報
4. 怠報金
    - 自始至終沒有申報
5. 罰鍰
    - 行爲罰
    - 漏稅罰
    - \#503 法治國原則導出之**一行爲不二罰**，針對同一個行爲的非難，不能重複非難
      - 重複非難禁止（德文：重複評價禁止）
      - 一行爲不二次非難
      - 一個人的同一行爲不被國家進行裁罰性質的重複非難
      - 不對構成要件與法律結果進行重複非難
      - 不在不同法領域重複非難
    - 滯納金（不利益，不具裁罰屬性）與罰鍰，并不受**一行爲不二罰**之規範


特別公課的附加：

- 不具裁罰性質，不需要主觀可歸責的事由，不考慮可歸責性
- “不知法律”不構成免除其公課負擔之事由

# W02_0228

連假

# W03_0307

續上周

區分行政處分具有裁罰屬性 之

主觀上無可非難之事由


同一份函令包含數個行政處分之行爲，息息相關，數額計算之依據

補稅的行政處分
（應申報未申報，按其所漏稅額，計算）漏稅罰罰鍰處分

納稅人在救濟時若分開提起行政救濟，若只針對罰鍰提起救濟，則法官不對已具有形式存續力的補稅處分進行審查，僅對後者漏稅罰罰鍰處分部分進行審查。

法律要件該當時，即已經發生法律上權利義務關係，行政處分只是確認【已經形成的】法律上權利義務關係

區分

- 權力關係說
  - 法律槼範給行政機關一個行政權限，而形成與人民之間的權利義務關係
  - 課稅處分形成國家與人民之間之權利義務關係
  - 警察法
    - 警察在個案中，選擇何種法律效果（例如，是否攔查闖紅燈的行爲人，警察斟酌個別情況決定是否）
    - 便宜原則，讓行政機關在個案，即使法律要件該當時，仍然可以決定，是否、如何形成與人民之間之權利義務關係
    - 決定裁量權限
- 法律關係說
  - 法律要件該當時，即已經發生法律上權利義務關係，行政處分只是確認【已經形成的】法律上權利義務關係
  - 課稅處分只是作爲確認（兼具命給付）性質之行政處分

隨著德國魏瑪憲法，以稅捐為内容的權利義務關係采納【法律關係說】，這種看法，慢慢對日本、台灣的影響
台灣憲法19，依法課稅原則，以法律關係說作爲憲法上的依據，行政機關并不享有裁量權限，在法律構成要件滿足時，必作成課稅處分
沒有裁量與否的空間
執行的誡命
行政機關不得偏離稅法的規範
偏離禁止（不准偏離軌道）

行政機關具有依據對於依法形成的稅捐債權債務關係而做成課稅處分之義務

但這并非法治國家之共同看法

美國就容許行政機關具有裁量空間，可以選擇，對於依法形成的稅捐債權債務關係，是否、如何做成課稅處分


稅捐是一種法定之債，具有各項構成要件之要素、法律效果，都是依據法律明訂。

四項構成要件

- 稅捐主體
- 稅捐客體
- 稅基
- 稅率

各個構成要件散佈在各稅法，去做規範

立法者沒有按照體系、條文排列沒有順序！

稅法在立法時間較爲後面，立法技術極爲拙劣、讓稅法變得難以學習的背景

法條是散的，分散式立法不像民法各論（民法的條文規範有邏輯、有順序）、刑法分則

老師的工作是要把支離破碎的稅法，通過體系的重新整理，讓同學有邏輯地學習

稅法應該要長得比較好看一點，應該要有一部統一的稅法典，去厘清各稅目之間額關聯（例如遺產與贈與稅之間之關係）

同學可以做一項工作

將各稅法（所得稅、遺產及贈與稅、營業稅）
針對其中所規範之構成要件
將所有的稅法的法條去做重新的排列組合

各稅之該當，應符合對應之課稅構成要件

搞清楚稅捐債權債務關係的請求權基礎

遺產及贈與稅，以遺產稅爲例


- 稅捐主體 （原則上應該是拿到遺產的人）
- 稅捐客體（你拿到的遺產）
- 稅基（遺產之數額，量化才能算數額，要腦筋清楚，要辨別哪些是應稅）
- 稅率（課徵之比例）



贈與稅

- 稅捐主體 （原則上應該是拿到錢的人，才有ability to pay嘛！應該要以受贈人為納稅義務人，但是法律不是這樣規定）
- 稅捐客體（你拿到的遺產）
- 稅基（遺產之數額，量化才能算數額，要腦筋清楚，要辨別哪些是應稅）
- 稅率（課徵之比例）


土地稅（財產稅）

- 稅捐主體 （擁有土地的所有人）
- 稅捐客體（土地）
- 稅基（土地的價值）
- 稅率（課徵之比例）

營業稅

- 稅捐主體 （銷售人）
- 稅捐客體（銷售）
- 稅基（貨物、勞務之銷售額）
- 稅率（課徵之比例）


稅捐法律效果

- 稅額 = 稅基 x 稅率
- 繳稅期間
- 稽徵程序
- 時效

稅捐優惠是反面的構成要件（構成要件或法律效果的反面的形態），給與納稅義務人在本來已經該當的構成要件之中，例外地加以排除

- 稅捐主體之 免除（100年前軍教人員薪水免稅（主+客））
- 稅捐客體之 免除（變動所得，出去打魚，一半課稅、一半免稅）
- 稅基之 減、免
- 稅率之 減、免（優惠稅率，自用住宅（10% -> 2%））
- 稅額的記存 （暫時不用繳納，條件成就時再繳納）
  - [土地增值稅](https://real-estate.get.com.tw/Columns/detail.aspx?no=905141) 指結算已發生之增值稅並記在帳上，於下次移轉時一併繳納，故已結算之增值稅部分不再發生累進稅作用。 如：都市更新權利變換關係人取得。


## 責任債務的給付請求

責任債務，實務的説法，在立法中未出現過這樣的字眼，

立法的描述：納稅義務人（明明是程序法概念，制定稅法的財政部，分不清實體法、程序法！所以立法的語言中都沒有出現 “稅捐債務人” 這樣的實體法概念）

學理上：稅捐債務人（根據稅法而形成的稅捐債權債務關係，實體法概念），從而在稽徵程序中是繳納義務人！（原則上，自己的稅捐債務，自己負擔申報繳納稅款的義務，自己是申報繳納稅款的義務人）

分別實意：
就源扣繳中有一個，扣繳義務人（不是稅法上應該負擔權利義務之主體，只是在程序上被拉進來作爲行爲義務之主體），以納稅義務人之名義

老師在臺大教書，臺大支付老師薪資100塊，老師是稅捐債務人，臺大是扣繳義務人（第三人的身份被拉近稅捐繳納的程序之中，非常的倒霉）
臺大不會全額支付給老師100塊，
在所得的源頭，就幫國家

非常倒霉！做好沒賞，打破要賠

沒有幫忙扣繳足額，則負擔補繳稅款的責任，這就是責任債務之概念

扣繳義務人，是以第二順位的責任債務人的身份而負擔補繳稅款的責任債務

稅捐債權人（財政收支劃分法中規範）

## 1435 補充

文化背景

> 看清朝的宮廷戯，徵稅，徵銀兩，法律規定收10兩，爲什麽收11兩？因爲火耗！熔掉碎銀兩，重新鑄的損耗，就跟人民多收
> 
> 大陸，包稅制！

如果還沒有像美國一樣的文化基礎，美國三權分立，行政有行政的權限，（在稅捐事務上有一定的裁量權限）

沒有辦法搬來一部分美國的法律制度。

美國的大法官，民選，台灣的法官是國家考試，如果也要民選，那麽要選法官就像選議員、首長一樣，要經營自己的選區XD

老師相信制度，但是制度要全面配套文化環境

若是退到50年前？要是給行政機關有裁量權限，會變成什麽樣子！
沒有健保時醫生排病床要紅包欸

美國的行政機關，有權限，不僅是權限，也是他的義務


法律規範密度不足，所以要看【法令匯編】

法律人的習慣是最低限度一定看法律，怎麽會解釋函令治國、解釋函令課稅？

立法委員的法律能力不足

實務上的具體操作，一定要看解釋函令，連老師也常常會不知道：欸有這樣的解釋函令欸！老師成大的學生，稅局的工作人員，只熟悉營所，不熟悉綜所！

如果不要求法律人用原理原則去操作，那就會變成看函令就好

30年以前，教稅法，不是叫法律人，而是叫經濟、會計...

稅捐主體，稅法的權利義務的歸屬主體！
國際稅法當中，誰是稅捐主體？PE常設機構是稅捐主體。

法律人自己不認真把稅法當作法律，那麽別人就會來幫忙你詮釋！

稅法變成這樣，是因爲法律人不認真對待稅法，自己不在乎！

房價爲什麽那麽高，炒地皮不用負擔那麽多稅！

老師讀書的時候，信義區只有一棟高樓，臺北市政府，我也知道買地皮可以賺錢！但是...

稅捐正義！有所得不課稅，還講什麽爭議，非常可笑的事情。

証交稅，怎麽可能代替，証所稅？！

大法官解釋，証交稅代証所稅，是因爲立法理由這樣寫，爲什麽立法理由寫這麽離譜，因爲...

爲了証所稅，犧牲了2個財政部長!

要証所稅，股市跌下來，就嚇到了，

我要是財政部長，誰在那邊炒作，就立馬把你抓過來~

香港本來的立足點就跟台灣不一樣

這個國家對於自己的立足點、定位不清楚。

稅法本來不該這邊麽丑！

> 島上的猴子都1只眼睛，就會覺得1眼是正常的，去其他地方看到2只眼睛的猴子，還會覺得2只眼睛是奇怪的。

稅法是很重要的分配正義的起點。

國家不事生產，不是生產的主體，國家是分配組織，不應該期待國家10塊錢生出100塊，頂多是10塊錢出來2~10塊，看組織的效率、貪腐？

稅收分配 關係到國家的收跟支...
形式合法性，實質正當性（量能，有賺錢就交稅，有虧錢就扣除）

老師講話那麽憤慨，其實是恨自己沒有多個分身，去將稅捐正義、分配正義的重要性（QQ

不是所有東西都是市場經濟可以做得到。

老師希望稅法不是只有大學生來上，

因爲政治經濟的因素而不能上到大學

香港，膠囊的公寓，人還有什麽....這不是一個人該被對待的方式，我的天，這什麽世界

（T^T

請各位不要輕易放棄稅法，講分配正義，沒有稅法不行


## 回到責任債務人

    所得稅法94

    第 94 條
    扣繳義務人於扣繳稅款時，應隨時通知納稅義務人，並依第九十二條之規定，填具扣繳憑單，發給納稅義務人。如原扣稅額與稽徵機關核定稅額不符時，扣繳義務人於繳納稅款後，應將溢扣之款，退還納稅義務人。不足之數，由扣繳義務人補繳，但扣繳義務人得向納稅義務人追償之。



**不足之數，由扣繳義務人補繳**
【責任債務之概念】

**但扣繳義務人得向納稅義務人追償之**
【看起來好像回復正義】，但是，
追繳不用錢嗎？追繳一定追得到嗎？

納稅義務人可能死了，可能不給錢，追償可能要打官司，告納稅義務人，要成本呢

看這種條文看起來火大



中科院

退伍的軍人，做研究，薪水蠻好的

中科院主管單位認爲，比照軍人免稅（其實退伍之後就不是軍人了，是雇傭契約），中科院以爲免稅，沒有扣繳，83年-85年，上萬的人沒有扣繳，財政部突然發現，這些人怎麽長達5年全部沒有繳稅？
總共補繳7E，再加罰三倍21E應扣未扣

114

    第 114 條

    扣繳義務人如有下列情事之一者，分別依各該款規定處罰：
    一、扣繳義務人未依第八十八條規定扣繳稅款者，除限期責令補繳應扣未扣或短扣之稅款及補報扣繳憑單外，並按應扣未扣或短扣之稅額處一倍以下之罰鍰；其未於限期內補繳應扣未扣或短扣之稅款，或不按實補報扣繳憑單者，應按應扣未扣或短扣之稅額處三倍以下之罰鍰。
    二、扣繳義務人已依本法扣繳稅款，而未依第九十二條規定之期限按實填報或填發扣繳憑單者，除限期責令補報或填發外，應按扣繳稅額處百分之二十之罰鍰。但最高不得超過二萬元，最低不得少於一千五百元；逾期自動申報或填發者，減半處罰。經稽徵機關限期責令補報或填發扣繳憑單，扣繳義務人未依限按實補報或填發者，應按扣繳稅額處三倍以下之罰鍰。但最高不得超過四萬五千元，最低不得少於三千元。
    三、扣繳義務人逾第九十二條規定期限繳納所扣稅款者，每逾二日加徵百分之一滯納金。


會計、出納單位

釋字第673 號 居然説這兩個都合憲欸

人家是沒做好沒錯，但要他補繳、要賠？！

    稅捐稽徵法 第 42 條

    代徵人或扣繳義務人以詐術或其他不正當方法匿報、短報、短徵或不為代徵或扣繳稅捐者，處五年以下有期徒刑、拘役或科或併科新臺幣六萬元以下罰金。
    代徵人或扣繳義務人侵占已代繳或已扣繳之稅捐者，亦同。

請問這本來是誰的公法義務啊？太誇張！（@#￥！&

應該是納稅義務人首先負擔補繳責任！

德國：連帶債務人

責任債務應該的特徵，理論上

- 補充性：后順位被追償
- 從屬性：責任債務的範圍不大於主債務的範圍


但是法律明文規定：遺囑執行人、遺產管理人

遺產稅 6（1）反客爲主？！

    第 6 條
    遺產稅之納稅義務人如左：
    一、有遺囑執行人者，為遺囑執行人。
    二、無遺囑執行人者，為繼承人及受遺贈人。
    三、無遺囑執行人及繼承人者，為依法選定遺產管理人。
    其應選定遺產管理人，於死亡發生之日起六個月內未經選定呈報法院者，或因特定原因不能選定者，稽徵機關得依非訟事件法之規定，申請法院指定遺產管理人。


遺囑執行人、遺產管理人，只是職務管理人，變成遺產稅的納稅義務人？！
其實是應盡一個職務管理人的責任，要先交完稅，再把剩下的遺產分配給繼承人及受遺贈人

應該還是要以繼承人及受遺贈人，為
后順位才是以遺囑執行人、遺產管理人，作爲責任債務人的身份而負擔這樣的不利益


## 下周講 溢繳稅款返還稅款請求 vs. 退給稅款的給付請求

