# W04_0314 溢繳稅款返還請求 vs. 退給稅款的給付請求

## 退給稅款

一定有法律槼範作爲依據

### 第一種類型：

暫繳、扣繳稅款

國外（所得來源國）稅款扣抵（稅籍國）國内稅款

### 第二種：稅捐優惠的退給稅款

基於某種政策目的（經濟、文化、教育、慈善，
給予納稅義務人的稅捐優惠

在一些情況，不以稅為名，各領域的行政法（實質稅法，不是出現在稅法中），提供相對應的稅捐優惠、鼓勵人們選擇某種行爲

環境保護領域，個人或企業做出政策所鼓勵的行爲，

稅法本身也有提供稅捐優惠，最典型的，自用住宅的重購退稅，在我們的房地分立的時代（105年以前），在房屋中適用重購退稅，所得稅法17-2

土地，自用住宅重購退，土地稅法35

105之後，改成房地合一，所得稅法14-8第一項的規定

> hw 重購退稅105年以前房地分立之下以及 105年以後房地合一的重購退稅，兩軌，整理法規範依據，將其構成要件、法律效果之解析，比較、對照【何謂自住】
> 這是依法課稅非常重要的
> 先不管立法者爲什麽要分立這麽多條規定
> 先不談違反平等原則的問題（同一個概念之下的土地財產交易所得，做區別的對待，盈餘虧損不能互相扣抵，稅率
>
> 要不要交這個功課，悉聽尊便，但是，考試的時候，期末考會考的~
> 這個作業，其實本來應該要立法者來做的，但是立法者不僅沒有整合對照，反而分開兩軌

重購退稅，原本是社會政策，政策目的，鼓勵人們換房子，從小換到大，鼓勵人們改善自己的生活環境

政策目的是否符合社會現況？房地價格急速飆漲，往往換來的并非更好的生活環境，買了新的，極可能居住面積只能更狹小。

> 自主的事實要則麽證明？
> 要不要設立戶籍？
> 不需要設立，因爲戶籍只是行政管理措施
> 那麽到底要證明是自主？要用經濟實質的角度去證明？沒有適合的方法？每天去盯梢？警察天天去查戶口？
> 徵納雙方之間就“是否具居住之事實”而產生爭執
>
> 納稅義務人原則上要去證明“自主的事實”，以及滿足相關的期間的規定，而主張因構成要件之該當，適用重購退稅，而在申報是，申報自繳稅額爲零【本質上是退給稅款】

## 不當得利的稅款返還

有單一的法律規定！

> 稅捐稽徵法 第 28 條
> 
> 1. 因適用法令、認定事實、計算或其他原因之錯誤，致溢繳稅款者，納稅義務人得自繳納之日起十年內提出具體證明，申請退還；屆期未申請者，不得再行申請。但因可歸責於政府機關之錯誤，致溢繳稅款者，其退稅請求權自繳納之日起十五年間不行使而消滅。
> 
> 2. **稅捐稽徵機關於前項規定期間內知有錯誤原因者，應自知有錯誤原因之日起二年內查明退還。**
> 
> 3. 納稅義務人對核定稅捐處分不服，依法提起行政救濟，經行政法院實體判決確定者，不適用前二項規定。
> 
> 4. 第一項規定溢繳之稅款，納稅義務人以現金繳納者，應自其繳納該項稅款之日起，至填發收入退還書或國庫支票之日止，按溢繳之稅額，依各年度一月一日郵政儲金一年期定期儲金固定利率，按日加計利息，一併退還。
> 
> 5. 中華民國一百十年十一月三十日修正之本條文施行時，因修正施行前第一項事由致溢繳稅款，尚未逾五年之申請退還期間者，適用修正施行後之第一項本文規定；因修正施行前第二項事由致溢繳稅款者，應自修正施行之日起十五年內申請退還。
> 
> 6. 中華民國一百十年十一月三十日修正之本條文施行前，因修正施行前第一項或第二項事由致溢繳稅款者，於修正施行後申請退還，或於修正施行前已申請尚未退還或已退還尚未確定案件，適用第四項規定加計利息一併退還。但修正施行前之規定有利於納稅義務人者，適用修正施行前之規定。
> 
> 7. 行為人明知無納稅義務，違反稅法或其他法律規定所繳納之款項，不得依第一項規定請求返還。

法條的用字用了非常抽象的【退稅】（很容易形成誤導），應該叫做【溢繳稅款的返還】


構成要件：

區別：是否因可歸責於政府機關之錯誤

消滅時效（期間）的差異！

起算日：繳納之日
期間： 10年v.s. 15年（若錯誤來自於我們的政府機關，則期間延長至15年）


【可歸責於（我們的）政府機關】之反面，并非【可歸責於納稅義務人】

e.g. 第三人：外國機關

錯誤類型：

- 適用法令之錯誤
- 認定事實之錯誤
- 計算或其他原因之錯誤

110年12月30修正，將各項錯誤都寫上去，是想表示，不管什麽原因的錯誤，只有這3種類型

有差額（課稅處分所載之稅額，大於依稅法規定，滿足構成要件所形成（發生）之稅捐債務數額），就代表【溢繳稅款】的情形


- **28條第3項**
- 納稅義務人對核定稅捐處分不服，依法提起行政救濟，**經行政法院實體判決確定**者，不適用前二項規定。

統一處理：（舊法時）納稅義務人無視行政法院裁判既判力，而提起溢繳稅款的返還的請求

- 【溢繳稅款的返還】是否有程序法上之意義？
- 行政處分原本是有救濟可能性，納稅義務人應該依據行政程序而進行行政救濟，
- 在舊法時代，納稅義務人一再無視行政處分之形式存續力、既判例，而提起【溢繳稅款的返還請求】
- 新法：納稅義務人對核定稅捐處分不服，依法提起行政救濟，**經行政法院【實體判決】確定**（行政法院裁判既判力）者，【排除】【溢繳稅款的返還請求】

仍然可能提起【溢繳稅款的返還請求】的可能性：

1. 納稅義務人在前程序，行政處分做成之後，沒有提起行政救濟。
2. 就算經由行政救濟程序，只要沒有進入行政法院的行政訴訟【e.g.提起訴願，被駁回】
3. 納稅義務人已提起行政訴訟，但是行政法院只是（形式上的）裁定駁回（e.g.預約期間、欠費）


即，一旦不具【行政法院裁判既判力】，即可提起【溢繳稅款的返還請求】

與 **行政程序法128條，程序再開【3個月内】** 不合

而有些稅捐之徵收，在我國沒有行政處分，e.g. 娛樂稅（代徵）契稅（銷花）
以往沒有救濟的管道。即28條第1項，原始的適用情形。


整理

- 有稅捐之行政處分：
  - 行政處分形式存續力+實體判決既判力：28第3項，不得提起【溢繳稅款的返還請求】
  - 行政處分形式存續力，無實體判決：得提起【溢繳稅款的返還請求】

- 無行政處分：
  - 得依28條第1項提起【溢繳稅款的返還請求】


【28條第7項】

行為人明知無納稅義務，違反稅法或其他法律規定所繳納之款項，不得依第一項規定請求返還。

對照民法上明知自己沒有給付的義務（180），不當得利之排除【不當得利是整個法秩序中，所有的調整權利義務之最後一項機制】

以前沒有【28條第7項】時，要類推適用民法

e.g. 納稅義務人幫助其他納稅義務人逃漏稅捐：開假發票，變成別人的加成本，虛報進項稅額。【本質上是幫助犯，但是稅捐的體系中幾乎沒有針對幫助犯的規範】

組織型的逃漏稅捐的情形，旋轉木馬的形式，拿到最多銷商稅額的公司，倒閉

> 德國：旋轉木馬的把戲，如果稽徵機關效率高，就不太容易發生

以前針對這個是用【誠信原則】，現在就用法律依據，法律明文規定，

# 稅捐稽徵法【是整個稅捐法制中的重中之重】 0314-1443

稅捐稽徵：確認（以法律所形成之）稅捐債務關係

## **依法課稅**（的内涵包含程序合法性）

- 課稅要件（稅捐債務）法定
- 稽徵程序法定

對於稅捐稽徵機關：【偏離禁止、適用誡命】
一定要做，沒有可以讓他不做的空間

稅捐稽徵法：是一種手段法

### 比例原則

手段不能逾越目的、不能逾越**比例原則**，不能只是爲了課稅而過分干預人民權利

課稅手段不能逾越課稅目的，比例原則的思考，也是重要的憲法原則，但是不太有功能！
比例原則，在一般的干預行政法體系中，是最重要的憲法原則。

e.g. 警察法，

稅的本質，已經肯認了國家對於財產權的干預，但是禁止過度的干預【絞殺稅、寓禁於徵禁止（法治國家不允許這種手段）】，比例原則的適用限度僅限於此，沒有其他具體的適用情形，沒辦法有更好的違憲審查的作用

排放戴奧辛、毒品販賣、人口、强制【禁止】
v.s
烟草消費【開放但不鼓勵】


稅捐本來是中立的，如果要完全禁止，就不能用稅！

但是稅捐、公課手段可以有政策目的，而有較重的稅捐負擔或稅捐優惠

- 【禁止】不能用稅的手段來實現，要用刑事手段
- 【開放但是不鼓勵】從而是用比較高的稅負，用經濟手段誘導人們的行爲

### 平等原則

相比起來，**平等原則**是更重要的憲法原則！

同樣是納稅義務人，爲啥甲和乙的稅捐負擔不同。

量能課稅【更具體化**平等原則**】

平等原則是以量能課稅（及各項子原則）而具體化，這樣才能實際操作


維繫個人生存需求


## 稅捐稽徵程序之法律槼範

課稅行政處分是一個確認兼命給付之行政處分，可以作爲行政執行之依據

稅捐稽徵程序，在我國，呈現分立的立法，分散式立法，

- 稅捐稽徵法（原則性規範立法較早）
- 各稅法中關於稽徵程序之規定
- 行政程序法（較晚，變成行政程序的普通法，補充性的法律規定）
- 納稅者權利保護法（以納稅者權利保護爲名）
   
極其分散式的立法

> 以前行政程序法還沒制定的時候，沒有行政程序法可以念，只能以稅捐稽徵法為例

集中式立法比起分散式立法更能夠進行體系上的整理、對照

簡單來講，這幾個法律（同位階的）的適用先後順序

1. 納稅者權利保護法，優先規定
2. 各稅法中關於稽徵程序之規定
3. 稅捐稽徵法
4. 行政程序法（補充稅捐稽徵法不足之處，e.g.程序重開）

> - 特別法由於普通法
> - 後法優於先法
> - 後法的一辦法，沒有由於先法的特別法，除非有明文規定（e.g.28第7項）

## 下禮拜再繼續説明，我們的稅捐稽徵程序規範真的是爛...到...爆...爛到不行（XD

稅捐稽徵程序的不同類型、三個不同階段




