

# W05_0321 稅捐稽徵程序

1. 核課
2. 徵收（保全）
3. 執行（由行政執行署而主管）

## 核課期間（最重要的程序階段）

SJF

> 第 21 條
> 
> 1. 稅捐之核課期間，依下列規定：
> 一、依法應由納稅義務人申報繳納之稅捐，已在規定期間內申報，且無故意以詐欺或其他不正當方法逃漏稅捐者，其核課期間為五年。
> 二、依法應由納稅義務人實貼之印花稅，及應由稅捐稽徵機關依稅籍底冊或查得資料核定課徵之稅捐，其核課期間為五年。
> 三、未於規定期間內申報，或故意以詐欺或其他不正當方法逃漏稅捐者，其核課期間為七年。
> 2. 在前項核課期間內，經另發現應徵之稅捐者，仍應依法補徵或並予處罰；在核課期間內未經發現者，以後不得再補稅處罰。
> 3. 稅捐之核課期間屆滿時，有下列情形之一者，其時效不完成：
> 一、納稅義務人對核定稅捐處分提起行政救濟尚未終結者，自核定稅捐處分經訴願或行政訴訟撤銷須另為處分確定之日起算一年內。
> 二、因天災、事變或不可抗力之事由致未能作成核定稅捐處分者，自妨礙事由消滅之日起算六個月內。


形成權？ 請求權？

- 除斥期間說
  - 權力關係說
- 消滅時效說
  - 法律關係說
  - 以金錢為内容的給付請求
  - 債上請求
  
- 【消滅時效說】時效期間
  - 是否有時效障礙的問題
  - 是否存在【妨害時效起算、終止】的相關規定？

- 納稅義務人未申報
- 納稅義務人提起救濟、進入行政爭訟救濟程序
    - 撤銷廢棄
    - 行政處分自始不生效力
    - 【以前沒有時效障礙規定時】納保法21條4項
    - 比照刑事妥速
    - 從第一審撤銷發回時起算，總共15年的時間
    - 解決行政處分做成之後，納稅人對其提起行政救濟程序
    - 納保法施行細則【第10條第1項第2款】【雖然沒有廢止，但是實際上沒有適用的可能】
    - > 第 10 條
      >
      > 1. 本法第二十一條第四項所定自法院作成撤銷或變更裁判之日起逾十五年未能確定其應納稅額者，不得再行核課，該十五年之起算日，依下列規定：
      > 一、本法施行後法院最初作成撤銷或變更裁判之日。
      > 二、納稅者對於第一審終局裁判提起上訴或抗告，於本法施行後經上級行政法院最初作成廢棄原裁判之日。
      > 2. 前項所稱作成撤銷、變更或廢棄原裁判之日，指宣示日；其不宣示者，為公告日。
      > 本法第二十一條第四項但書所稱不在此限，指不受十五年不得再行核課期間之限制。
    - 【老師評：不倫不類，太荒謬了，越算越久！原本5年變15年】
    - 【現，110-12-17】SJF第21條3項
    - > 稅捐之核課期間屆滿時，有下列情形之一者，其時效不完成：
        >
        > - 一、納稅義務人對核定稅捐處分提起行政救濟尚未終結者，自核定稅捐處分經訴願或行政訴訟撤銷須另為處分確定之日起算**一年**內。
        > - 二、因天災、事變或不可抗力之事由致未能作成核定稅捐處分者，自妨礙事由消滅之日起算**六個月**內。

    - 【終止的不完成】用不完成的方式，當障礙事由被排除，再給他一段額外的，請求權利的時效期間
    - 現在終於可以在行政訴訟實務上，可以連原處分一并撤銷【+復查+訴願】

- 現在終於可以在行政訴訟實務上，可以連原處分一并撤銷【+復查+訴願】
    - 法院認爲稅捐稽徵機關無理由：
    - 直接撤銷
    - 撤銷發回
        - 行政法院仍要進行事實調查
            - 又行政機關進行跨境的事實調查
  
- SJF第22條6款
    - > 六、稅捐減免所依據處分、事實事後發生變更、不存在或所負擔義務事後未履行，致應補徵或追繳稅款，或其他無法依前五款規定起算核課期間者，自核課權可行使之日起算。
    - 僅就【稅捐減免、稅捐優惠】
    - 不包含【納稅義務人未申報】的情形
    - 應該要有：【自核課權可形式之日起算】
        - 常常用【解釋函令】的方式
        - 將起算點，由（22T1X1K）【申報日】（依規定申報者）或【規定申報期間屆滿之翌日】（未在規定期間內申報繳納者）
- > 第 22 條
    > 前條第一項核課期間之起算，依下列規定：
    > 一、依法應由納稅義務人申報繳納之稅捐，已在規定期間內申報者，自**申報日**起算。
    > 二、依法應由納稅義務人申報繳納之稅捐，未在規定期間內申報繳納者，自**規定申報期間屆滿之翌日**起算。
- 依規定申報者
    - 起算點：【申報日】
    - 期間：21T1X1K
    - 5年
- 未在規定期間內申報繳納者
    - 起算點：【規定申報期間屆滿之翌日】
    - 期間：21T1X3K
    - 7年
- 故意以詐欺或其他不正當方法逃漏稅捐者
    - 起算點：【申報日】
    - 期間：21T1X3K
    - 7年

幾種類型

1. 短報收入
   - 老師認爲：
      1. 對於所得來源做誠實的告知，或許是處於法律間接的歧義，不算
   - 數額的短少
   - 虛增成本費用
   - 實務上認爲屬於【21T1X3K 故意以詐欺或其他不正當方法逃漏稅捐者】
      - 申報數額需要提供確信的法律見解：爲什麽少報那20萬？
      - 以自以爲是的法律見解，而短報，屬於【21T1X3K 故意以詐欺或其他不正當方法逃漏稅捐者】
2. 漏報
   1. 納稅者有多處所得來源，但僅報其中部分，【對所得來源的不完全申報】
   2. 老師認爲其惡性高於短報
3. 稅捐規避
   - 實務上： 屬於【21T1X3K 故意以詐欺或其他不正當方法逃漏稅捐者】（不區分有否隱匿事實）
   - 老師：【應該區分納稅義務人是否有隱匿其法律行爲的安排事實】
     - 稅捐規避若并未隱匿課稅事實，是一種取巧的安排【濫用法律形成，每一個法律形成都是真的】，而應該適用【21T1X1K】5年
     - 21T1X1K及3K之區別 
       - 是因爲課稅構成要件事實之隱匿，稅捐稽徵機關才需要更多的時間去做實施、證據的調查
     - e.g. 我是律師，我向基金會提供法律顧問【應稅的執行業務所得】，但約定，由基金會提供相當數額的獎學金予我的孩子
       - 將【應稅的執行業務所得】，轉換成孩子的獎學金
     - 若申報時有誠實告知事實，只能評價為規避
       - 稅捐急症機關不需要更多的時間去做事實證據的調查
       - 老師認爲應該適用【21T1X1K】5年
     - 但是事實上，納稅義務人在做【規避】時，并沒有誠實告知其路徑的安排！ （通常自己心有鬼）
       - 就會變成該當【21T1X3K 故意以詐欺或其他不正當方法逃漏稅捐者】——7年的期間

遺產及贈與稅

納稅義務人若沒有完全申報，但躲過了7年，便時效完成

借名行爲
有時候繼承人自己也不知道被繼承人的財產狀況
但有時候繼承人是明知有借名行爲，但隱匿

可不可能用22T6K？

- SJF第22條6款
 - > 六、稅捐減免所依據處分、事實事後發生變更、不存在或所負擔義務事後未履行，致應補徵或追繳稅款，或**其他無法依前五款規定起算核課期間者**，自**核課權可行使之日**起算。
- 是否包含【借名行爲】？
  - 前段不算，後段有沒有可能？
- 實務上還沒有定論
- 實務有見解：核課期間是保護納稅義務人對於法安定性的信賴，稅捐稽徵機關不得以此，以推後起算點而在實質上延長期間
- 在法律的價值上有些鼓勵人們盡力地隱匿事實

## 徵收時間之時效

保全：

> 第 23 條
> 
> 1. 稅捐之徵收期間為五年，自繳納期間屆滿之翌日起算；應徵之稅捐未於徵收期間徵起者，不得再行徵收。但於徵收期間屆滿前，已移送執行，或已依強制執行法規定聲明參與分配，或已依破產法規定申報債權尚未結案者，不在此限。
> 2. 應徵之稅捐，有第十條、第二十五條、第二十六條至第二十七條規定情事者，前項徵收期間，自各該變更繳納期間屆滿之翌日起算。
> 3. 依第三十九條暫緩移送執行或其他法律規定停止稅捐之執行者，第一項徵收期間之計算，應扣除暫緩執行或停止執行之期間。
> 4. 稅捐之徵收，於徵收期間屆滿前已移送執行者，自徵收期間屆滿之翌日起，五年內未經執行者，不再執行；其於五年期間屆滿前已開始執行，仍得繼續執行，但自五年期間屆滿之日起已逾五年尚未執行終結者，不得再執行。
> 5. 本法中華民國九十六年三月五日修正前已移送執行尚未終結之案件，自修正之日起逾五年尚未執行終結者，不再執行。但截至一百零六年三月四日納稅義務人欠繳稅捐金額達新臺幣一千萬元或執行期間有下列情形之一者，仍得繼續執行，其執行期間不得逾一百二十一年三月四日：
> 一、行政執行分署依行政執行法第十七條規定，聲請法院裁定拘提或管收義務人確定。
> 二、行政執行分署依行政執行法第十七條之一第一項規定，對義務人核發禁止命令。

老師：盡可能明確地表示你的法規範依據：

23T1X1J1FJ

23條第1項第1句第1分句

SJF49T1X1J

徵收期間之内的行政行爲是做什麽？

- 保全
- 在進入行政執行之前，保護國家債權之實現
- 物的保全24T1X
- 人的保全24T3X

> 第 24 條
> 
> 1.稅捐稽徵機關得依下列規定實施稅捐保全措施。但已提供相當擔保者，不適用之：
> 一、納稅義務人欠繳應納稅捐者，稅捐稽徵機關得就納稅義務人相當於應繳稅捐數額之財產，通知有關機關，不得為移轉或設定他項權利；其為營利事業者，並得通知主管機關限制其減資之登記。
> 二、納稅義務人有隱匿或移轉財產、逃避稅捐執行之跡象者，稅捐稽徵機關得於繳納通知文書送達後，聲請法院就其財產實施假扣押，並免提供擔保；其屬納稅義務人已依法申報而未繳納稅捐者，稅捐稽徵機關得於法定繳納期間屆滿後聲請假扣押。
> 2. 納稅義務人之財產經依前項規定實施稅捐保全措施後，有下列各款情形之一者，稅捐稽徵機關應於其範圍內辦理該保全措施之解除：
> 一、納稅義務人已自行或由第三人提供相當擔保。
> 二、納稅義務人對核定稅捐處分依法提起行政救濟，經訴願或行政訴訟撤銷確定。但撤銷後須另為處分，且納稅義務人有隱匿或移轉財產、逃避稅捐執行之跡象，不辦理解除。
> 3. 在中華民國境內居住之個人或在中華民國境內之營利事業，其已確定之應納稅捐逾法定繳納期限尚未繳納完畢，所欠繳稅款及已確定之罰鍰單計或合計，個人在新臺幣一百萬元以上，營利事業在新臺幣二百萬元以上者；其在行政救濟程序終結前，個人在新臺幣一百五十萬元以上，營利事業在新臺幣三百萬元以上，得由財政部函請內政部移民署限制其出境；其為營利事業者，得限制其負責人出境，並應依下列規定辦理。但已提供相當擔保者，或稅捐稽徵機關未實施第一項第一款前段或第二款規定之稅捐保全措施者，不適用之：
> 一、財政部函請內政部移民署限制出境時，應同時以書面敘明理由並附記救濟程序通知當事人，依法送達。
> 二、限制出境之期間，自內政部移民署限制出境之日起，不得逾五年。
>

限制出境——會有2個主管機關
會被2個機關限制出境

- 法務部行政執行署——行政執行法第17條
- 財政部——稽徵法第24條第3項規定

配套規範不足，法律槼範非常貧瘠，國家法制上：越惡劣的人越能夠活得愉快

限制出境比限制住居所寬鬆得多！

孫道存
行政執行法第16 
後來增訂
第 17-1 條 禁奢條款

我們的民事執行法沒有限制出境的手段

德國的民事執行法就有限制出境

保全程序的核心概念：
稅捐稽徵機關要去**盡職調查**（DD），爲什麽剛開始課稅構成要件滿足時他有錢，但是在他要繳稅時卻沒錢了

> 在嚴謹的行政程序當中才是真正的的保護納稅人權利
> 人權保護不是喊口號，不是寫一個納稅人權利保護
> 而是把稅捐稽徵程序做細緻完整的規範
> 嚴謹的程序規定

法律規範的不足讓整個稅法的發展有許多的缺漏
我們需要一套完整的稅捐稽徵法的修法


## 執行期間

SJF規定執行程序是沒有道理的，因爲根本不在你的主管權限之内

行政執行機關是：
行政執行署

## 在各稅中

在各稅中有不同的課稅的類型，讓稅捐稽徵法看起來只對特定的稅目才有適用，但其實各稅的稽徵程序的規定完全沒有用到SJF，規範極爲混亂

各稅5種不同的稽徵程序


