# W06_0328

## 稅捐核課類型

總共可以整理出來5種不同的稅捐核課類型

陳清秀老師的書上，分成3類

1. （納稅義務人自行）申報 + 繳納 + 核課（核定）稅捐的行政處分or以公告的方式代替個別的核定稅捐行政處分的送達
   - 陳：申報繳納
   - 綜合所得稅往往是公告代替核定
2. （納稅義務人自行）申報 + 繳納
   - 印花稅、特銷稅、烟酒稅
   - 完全沒有任何核定稅捐的行政處分
3. 申報 + 核定 + 繳納
   - 陳清秀老師：申報復課
   - 遺產贈與稅、土地增值稅、契稅
4. 核定 + 繳納
   - 陳清秀：查定核課  
   - 納稅義務人不負擔申報協力義務，不需要納稅義務人的協力義務
     - 事後事實有所變更，納稅義務人有及時告知的義務？
   - 稅捐稽徵機關主動依據別的機關所保有的資料、憑證——【底冊稅】
   - 房屋稅
   - 非加值型營業稅
     - 小規模營業人
   - 納稅義務人可以主張信賴保護，就算稅捐稽徵機關沒有做正確的核課
5. 代徵的稅捐
   - 證交、期交、娛樂稅 
   - 完全看不到行政處分、也看不到稅捐稽徵機關
   - 公權力授予私人行使

行政處分

- 行政救濟的標的
- 信賴保護之基礎

當有行政處分，相對人就可以提起不服。不然就會有形式存續力的問題，會影響之後【已繳稅款返還權】

5種稽徵類型，看得出我們的稅法是多麽紊亂。

只要有核定稅捐的行政處分，就依據SJF35T1X【復查】SJF38T1X【訴願】

沒有核定處分，SJF28T

房屋稅稅率

- 住家用
  - 自住
  - 租住
- 非住家非營業用
  - 律師、會計師事務所、土地
  - 不要過於嘈雜即可
  - 小規模營業人的
- 營業用
  - 只要有任何營利事業登記在這


民98年，納稅義務人的房屋在不知情時被登記了營利事業，以營業用稅率

有核定稅捐行政處分，

徑自以SJF28，向稅捐稽徵機關請求溢繳稅款返還權
【完全無視其行政處分的形式存續力】

行政機關自撤其違法的行政處分【行政程序法117T】

SJF修正的歷史

> （舊）第二十八條
> 
> 1. 納稅義務人自行適用法令錯誤或計算錯誤溢繳之稅款，得自繳納之日起五年內提出具體證明，申請退還；屆期未申請者，不得再行申請。
> 1. 納稅義務人因稅捐稽徵機關適用法令錯誤、計算錯誤或其他可歸責於政府機關之錯誤，致溢繳稅款者，稅捐稽徵機關應自知有錯誤原因之日起二年內查明退還，其退還之稅款**不以五年內溢繳者為限**。
> 1. 前二項溢繳之稅款，納稅義務人以現金繳納者，應自其繳納該項稅款之日起，至填發收入退還書或國庫支票之日止，按溢繳之稅額，依繳納稅款之日郵政儲金一年期定期儲金固定利率，按日加計利息，一併退還。
> 1. 本條修正施行前，因第二項事由致溢繳稅款者，適用修正後之規定。
> 1. 前項情形，稅捐稽徵機關於本條修正施行前已知有錯誤之原因者，二年之退還期間，自本條修正施行之日起算。
>

【完全沒有時效限制】

終於在110年11月30日修正，填補了這樣的漏洞



核定稅捐，產生信賴保護

稅捐機關要受到自我束縛

納稅義務人信賴保護，要建立在

納稅義務人提供錯誤的資料、事實，不得主張信賴保護的適用，【沒有正當的信賴基礎】

稅捐稽徵機關

稅捐稽徵機關，是否有【事後查核權保留】？

爲什麽在依法課稅底下，允許行政機關做一個附附款的保留的行政行爲？

- 稅捐本質上是大量事件
- 證據資料往往偏向納稅義務人的支配範圍之内
- 在法有明文規定+行政行爲有明確的意思表示的情況下，允許行政行爲做出附副款的行政行爲。
- 在這一段期間之内，納稅人不得主張信賴保護


但是在台灣的稅法中，并沒有做出明文規定，關於稅捐稽徵機關得做附查核權保留，實務上的行政行爲也沒有明確的意思，要保留查核權

用法律解釋的方法：SJF21T2X1FJ

> 第 21 條
> 
> 1. 稅捐之核課期間，依下列規定：
>    一、依法應由納稅義務人申報繳納之稅捐，已在規定期間內申報，且無故意以詐欺或其他不正當方法逃漏稅捐者，其核課期間為五年。
>    二、依法應由納稅義務人實貼之印花稅，及應由稅捐稽徵機關依稅籍底冊或查得資料核定課徵之稅捐，其核課期間為五年。
>    三、未於規定期間內申報，或故意以詐欺或其他不正當方法逃漏稅捐者，其核課期間為七年。
> 1. 在前項核課期間內，經另發現應徵之稅捐者，仍應依法補徵或**並予處罰**；在核課期間內未經發現者，以後不得再補稅處罰。
> 



什麽是【另發現應徵之稅捐】
**納稅義務人是否有完全誠實的申報**？

- 納稅義務人申報事實之外之事實，可以導出應納之稅捐，納稅義務人沒有做誠實、完全的申報，構成稅捐稽徵機關補徵之正當基礎
- 若納稅義務人已完全誠實申報事實，但是以不同於稅捐機關的法律見解：
  - 法律見解的歧義——可以另補徵稅捐，但并不構成處罰的事由
  - 實務上：可以補稅，沒有裁罰
  - 老師：補稅也是違反信賴的！應該不能補稅、也不能裁罰

實務上：**揭露免罰**

- 誠實、及時、全面性地告知事實




我們的的核課稅捐的行政處分

- 核課稅捐的行政處分
- 核課期間内，補稅的行政處分

并存的數個（2個以上）行政處分，我們采取并存說

紛爭無法一次解決，導出多個行政救濟程序，裁判可能互相矛盾


用法律解釋的方法：SJF21T2X1FJ

并不自然導出【并存說】，可以像德國人的【以新代舊】
用新的行政處分取代舊的行政處分

實務上 用【并存說】而非【取代說】的理由

原來舊的，已經有形式存續力了，就不動他。

但是德國人的做法：舊的行政處分，舊的部分有形式存續力，不得主張不服。納稅義務人只能在新的行政處分新增加稅額的部分來聲明不服。

## 稽徵程序第二個階段：保全程序

保全程序

國家將來進入執行程序，能夠執行得到

在比例原則上是一個必要的程序

其實保全程序應該更早一些。

- 物的保全
- 人的保全

SJF24T1X

> 第 24 條
> 
> 1. 稅捐稽徵機關得依下列規定實施稅捐保全措施。但已提供相當擔保者，不適用之：
> 一、納稅義務人欠繳應納稅捐者，稅捐稽徵機關得就納稅義務人相當於應繳稅捐數額之財產，通知有關機關，不得為移轉或設定他項權利；其為營利事業者，並得通知主管機關限制其減資之登記。
> 二、納稅義務人有隱匿或移轉財產、逃避稅捐執行之跡象者，稅捐稽徵機關得於繳納通知文書送達後，聲請法院就其財產實施假扣押，並免提供擔保；其屬納稅義務人已依法申報而未繳納稅捐者，稅捐稽徵機關得於法定繳納期間屆滿後聲請假扣押。
> 

保全的範圍：【應繳稅捐數額】範圍内之財產+【49T：滯納金、利息、滯報金、怠報金及罰鍰】未實現稅捐債權之一切範圍：主給付+附帶給付（具裁罰+不具裁罰）

實務上采取這種最寬廣的解釋

老師：比較偏好：罰鍰應該不要包括，裁罰是對納稅義務人違反協力義務之制裁。
頂多是稅款本身和不具有非難性質之附帶給付之請求。

SJF49T

> 第 49 條
> 
> 1. 滯納金、利息、滯報金、怠報金及罰鍰等，除本法另有規定者外，準用本法有關稅捐之規定。但第六條關於稅捐優先及第二十六條之一第二項、第三十八條第二項、第三項關於加計利息之規定，對於滯報金、怠報金及罰鍰不在準用之列。
> 2. 中華民國一百十年十一月三十日修正之本條文施行前，已移送執行之滯報金及怠報金案件，其徵收之順序，適用修正施行前之規定。
>

第三人財產可以查封嗎？

第三人如果提供自己的財產作爲擔保，可以免除對於納稅義務人名下財產做保全

借名的財產？
在納稅義務人名下，但是納稅義務人只是出名人。怎麽處理？
老師：都要！借名行爲就是危險的。


24T1X1K其實只有特定的財產才有適用餘地：本質上是【假扣押】

【通知有關機關，不得為移轉或設定他項權利；其為營利事業者，並得通知主管機關限制其減資之登記。】

如果東西本身是私營事業，比如是上市貴股票，改上市貴公司，不是有關機關。集中保管公司？看起來集保公司是私營公司，但是他是負有公法上義務的。有所爭議。


其為營利事業者，並得通知主管機關限制其減資之登記。

24T1X2K才是真正的

不提供擔保的假扣押程序，本來就可以涵蓋24T1X1K，這2款是沒有意義的分類

假扣押就是限制移轉，限制做減資登記【禁止為特定行爲】，是假處分的概念。

跟民事法中的【假扣押（要錢）、假處分（要物）】

重點是要錢，假扣押才是重點的保全程序

下個禮拜：24T1X2K
+24T3X人的保全程序
+25T期前徵收