# W11_0502

登記-記賬-憑證-申報-配合調查

登記

- 營業稅：稅籍登記（營業稅法28T）

記賬憑證

- 營利事業：所得稅法21T
- 獨資合夥事業：
- 執行業務：所得稅法14T1X第二類第2段

---

申報稅

- 【報繳合一】 申報-繳納-核定/公告：綜所、營所、營業
- 【報繳分立】【陳：申報賦課】 申報-核定-繳納：遺產、贈與、土地增值（台灣沒有：附附款：事後查核權保留，）
- 【申報繳納】 

查定稅

- 【底冊稅】

代徵稅

- 沒有主管機關的出手：證交、期交、娛樂稅


申報稅，納稅人沒有隱匿課稅事實，但是其法律解釋（法律見解的歧義）導致他申報稅額有誤，是否有處罰性？

故意過失，是指對於課稅事實之誠實完全之申報

法律見解的歧義不構成可罰的事由，只有課稅構成要件的隱匿，才會導致可罰性。

事實和法律的交錯：對法律的解釋影響對事實的認定？怎麽辦？個案的判斷標準，納稅義務人在申報、過後配合調查的過程當中，去判斷（通常的法律解釋），納稅義務人是基於法律見解的歧義或基於隱匿事實之目的而未完全申報。


法律的適用是稅捐稽徵機關的職責。


法條的規定很抽象：

詐術、詐欺、或其他不正方法

是指對於課稅事實（課稅+免稅構成要件事實）的隱匿，

---

SJF 第 46 條

> 第 46 條
> 
> 1. 拒絕稅捐稽徵機關或財政部賦稅署指定之調查人員調查，或拒不提示有關課稅資料、文件者，處新臺幣三千元以上三萬元以下罰鍰。
> 
> 1. 納稅義務人經稅捐稽徵機關或財政部賦稅署指定之調查人員通知到達備詢，納稅義務人本人或受委任之合法代理人，如無正當理由而拒不到達備詢者，處新臺幣三千元以下罰鍰。


---

## 稅務協談

認識事實的手段有限。

稅務協談：沒有稅法法律明文，是行政規則的方式（協談作業要點），針對事實的認定，關於稅基，。稅務協談只能對於未知的事實，而不能與已知之事實顯然相背離。與已知之事實顯然相背離的協談是違反依法課稅原則的。徵、納雙方是協談的主體。

行政程序法136T，認定事實協議的行政契約，

有不同見解：陳敏老師，稅務協談不是行政程序法136T的行政契約，沒有契約的拘束力，只是參考，建議。但是基於誠信原則，對於雙方有拘束力。


老師：稅務協談就是行政程序法136T的行政契約，作業要點說沒有契約的拘束力，是不對的，應該改變。不僅僅是對於雙方的參考和建議，應該要有行政契約的拘束力。僅對徵、納雙方有拘束力，而不對法院有拘束力。法院是不受行政契約之拘束

德國：非行政契約，是基於誠信原則之拘束力。因爲德國的行政契約并沒有適用到稅捐法的領域。

---

## 推計課稅


相關的證據資料不存在，第一步還是要依職權調查（仍然屬於核實課稅），
用盡發現事實的手段，仍然有限，不足夠，則推計課稅

- 對於特定的交易：27T，推計成本、價格
- 對於全部的交易，帳簿、文據：83T1X1FJ，同業利潤標準



> 所得稅法 第 83 條
> 
> 1. 稽徵機關進行調查或復查時，納稅義務人應提示有關各種證明所得額之帳簿、文據；其未提示者，稽徵機關得依查得之資料或同業利潤標準，核定其所得額。
> 
> 1. 前項帳簿、文據，應由納稅義務人依稽徵機關規定時間，送交調查；其因特殊情形，經納稅義務人申請，或稽徵機關認有必要，得派員就地調查。
> 
> 1. 納稅義務人已依規定辦理結算申報，但於稽徵機關進行調查時，通知提示有關各種證明所得額之帳簿、文據而未依限期提示者，稽徵機關得依查得之資料或同業利潤標準核定其所得額；嗣後如經調查另行發現課稅資料，仍應依法辦理。
> 
> 
> 第 27 條
> 
> 1. 營利事業之進貨，未取得進貨憑證或未將進貨憑證保存，或按址查對不確者，稽徵機關得按當年度當地該項貨品之最低價格，核定其進貨成本。
> 1. 營利事業之銷貨，未給與他人銷貨憑證，或未將銷貨憑證存根保存者，稽徵機關得按當年度當地該項貨品之最高價格，核定其銷貨價格。

如果有憑證，則依憑證。
若無憑證，則（在市場價的範圍中）進貨成本從低、銷貨從高。【拉大你最大的利潤的可能】

依據什麽法理？禁止你從未盡義務之行爲中獲利。

盡義務本身就是成本。如果讓你可能因未盡義務而獲利，那麽還有誰要盡義務呢？就大家都不要盡義務就好啦！

只要做好保存賬簿憑證，就可以核實，核實一定會比推計更有利。

拉大你最大的利潤的可能，并非處罰納稅義務人！還是在市場價的範圍之中。


市場上一顆蘋果進貨價3到9塊，推計成本為3塊（最低市場成本）

c.f. 民法：中等品質、中間價格（推計為6塊）


### 同業利潤標準

全部範圍内的推計

- 毛利率 = 收入 - 成本
- 費用率
- 淨利率 = 毛利 - 費用

看你哪個部分不清楚，就適用哪個：成本不清楚，就用毛利率，費用不清楚，就用費用率算淨利率

應該要依據市場，實際查核，統計而來

但是現行同業利潤標準，是來自於同業公會的意見：各業納稅義務人所得額標準之核定，應徵詢各該業同業公會之意見。（SJF80T4X）

所以我們的同業利潤標準，都數十年不變。

#### 執行業務

國稅局用的收費標準：公會：一件4萬

當年的訂價，符合當時的社會行情


- 記賬：核實（可能是一件10萬）
- 不記賬：一件2.8萬（成本費用算3成）（是法扶的行情）

不記賬比較有利，所以大家都不記賬

應該要記賬！

老師評：同業利潤標準明明應該要是**最高之利潤可能**，但是卻變成藏污納垢的方式依據。

不記賬，在德國就是逃漏稅

> 一隻眼睛的猴子

核實才能達到量能，量能才能達到平等。

應該要貫徹協力義務。

