# W12_0509

經濟學、財政學的興趣主要在於稅率改革

而法律人更追求的是公平合理的稅基

## 推計課稅

### 擴大書審

> [擴大書審純益率是國稅局針對營業額在一定金額以下的中小企業，假如純益率達到標準，國稅局就會依所得額標準的方式予以書面審核，免予調帳。 書審純益率依據各企業行業別而有所不同，區間大約落在1%～10%之間，大部分的企業適用6%的純益率來計算、申報。](https://tongrencpa.com/filing-taxes/how-to-file-business-tax)

按照營業規模大小所作的利潤推計

- 3000萬以下，擴大書審純益率標準
- 3000萬以上，同業利潤標準的净利率


> 所得稅法
> 第 80 條
> 
> 1. 稽徵機關接到結算申報書後，應派員調查，核定其所得額及應納稅額。
> 1. 前項調查，稽徵機關得視當地納稅義務人之多寡採分業抽樣調查方法，核定各該業所得額之標準。
> 1. 納稅義務人申報之所得額如在前項規定標準以上，即以其原申報額為準。但如經稽徵機關發現申報異常或涉有匿報、短報或漏報所得額之情事，或申報之所得額不及前項規定標準者，得再個別調查核定之。
> 1. 各業納稅義務人所得額標準之核定，應徵詢各該業同業公會之意見。
> 1. 稽徵機關對所得稅案件進行**書面審核**、查帳審核與其他調查方式之辦法，及對影響所得額、應納稅額及稅額扣抵計算項目之查核準則，由財政部定之。

實際上，**書面審核**相關純益率標準，都是由各地國稅局所訂定，而非由財政部。并且沒有引述所得稅80T

這樣的情況受到批評，相關標準欠缺法律授權。


適用擴大書審純益率標準

假設某行業**書面審核**純益率6%

大家很聰明，就會報6%

- 報<6%，必查核（職權發動查核），被查到要提供賬簿憑證。
- 報>6%，抽查率：1%（職權發動查核），被查到，還是要要提供賬簿憑證。
  - 無提供完整的賬簿憑證，則改使用同業利潤標準的净利率（10%）
  - 納稅義務人主張：這是懲罰的推計課稅
  - 老師：完全錯誤的實務操作、完全錯誤的學説主張，這不是懲罰，你要主張適用更低的利潤率，就要記賬
    - 所謂懲罰，應該是使用市場上沒有的利潤。如果市場上最厲害的人利潤率才10%，稅局用20%來算，則可能具有裁罰屬性
    - 同業利潤標準，應該是市場上的最大利潤可能
    - 任何營利事業都有設賬記賬的
    - 推計應該是不利益，但不是裁罰
    - 設賬記賬當然會增加事業的財務上的負擔，【協力本身就是不利益的負擔】，可能不記賬，或者記賬不符合商業會計準則（簡單記給自己看的，内賬）。
    - 記得是内賬（不符合商業會計準則），也可以提示給稅局看呀，但是實務上不給看，因爲我就是賺得比

老師：這一套推計課稅很混亂。【推計的目的不是核實，而是用最大利潤可能】

想到以前輔大，實務課程的那個“老闆”，都教大家怎麽用利用這種擴大書審的制度，獲得租稅上的利益。

又想到，去問黃源浩老師的時候，老師説，不要聽業師的，他們都教怪怪的東西。現在更加懂了

以前業師上課就會説，利用一人公司、以及如果營業額高於3000萬，就拆分成低於3000萬的幾家公司

柯老師説，不能這樣亂教，老師也有各種的老師。這種教別人的，本質上是教唆。在德國，這種一人公司就會有法律的明文規定，去【穿透】，都歸屬到實質上的義務人。在台灣，沒有穿透的法律規定。穿透，很難通過法律解釋的方法去做實質課稅，還是應該要有法律明文規定才行。如果有【穿透】，則可以防止納稅人濫用這種一人公司的形態、拆分收入而獲取租稅上的利益。


> 納稅者權利保護法  第 14 條
> 
> 1. 稅捐稽徵機關對於課稅基礎，經調查仍不能確定或調查費用過鉅時，為維護課稅公平原則，得推計課稅，並應以書面敘明推計依據及計算資料。
> 1. 稅捐稽徵機關推計課稅，應斟酌與推計具有關聯性之一切重要事項，依合理客觀之程序及適切之方法為之。
> 1. 推計，有二種以上之方法時，應依最能**切近實額**之方法為之。
> 1. 納稅者已依稅法規定履行協力義務者，稅捐稽徵機關不得依推計結果處罰。【老師評：廢話】

老師：條文規定本身就很吊詭：推計的目的并不是**切近實額**，而是應該要推計為【最大利潤之可能】

老師：我希望能夠改變，但是一個人很難去改變這樣的現狀。這也是蠻遺憾的，稅捐負擔分配不均的問題。

推計方法【（協力義務之違反）查核不到才會用推計的】

- 内部推計法
  - 假定一個人的利潤不同年度不會相差太大
- 外部推計法
  - 同一商品、同類商品
  - 外部同業標準【同一個地區的同行】


處罰，應該是使用市場上沒有的利潤。如果市場上最厲害的人利潤率才10%，稅局用20%來算，則可能構成處罰。
