# W14_0523

下禮拜0530期末考試

2個實例綜合題目

1. 房地合一的退給稅款（構成要件）
2. 稅捐制裁、稅捐救濟


0606全面復習（上下學期）

稅捐法應該是一個整理的法體系

稅法不是法律系的必修

## 稅捐制裁法（延續上個禮拜）

前階段行爲并不當然被後階段行爲所吸收（刑法概念）。


### 逃漏稅捐罪

稅捐稽徵法41

> 第 41 條
> 
> 1. 納稅義務人以詐術或其他不正當方法逃漏稅捐者，處五年以下有期徒刑，併科新臺幣一千萬元以下罰金。
> 1. 犯前項之罪，個人逃漏稅額在新臺幣一千萬元以上，營利事業逃漏稅額在新臺幣五千萬元以上者，處一年以上七年以下有期徒刑，併科新臺幣一千萬元以上一億元以下罰金。

構成要件



#### 身份

德國：不是身份犯，任何人都會該當

台灣：
納稅義務人

納稅義務人如果是法人，但是自然人（負責人，本身不具有納稅義務人身份）幫法人去申報，在解釋上，如何理解，可否對此自然人施加逃漏稅捐罪的評價？

稅捐稽徵法47

> 第 47 條（本質上是【身份轉嫁】的規定，687號解釋）
> 
> 1. 本法關於納稅義務人、扣繳義務人及代徵人應處刑罰之規定，於下列之人適用之：
>   一、公司法規定之公司負責人。
>   二、有限合夥法規定之有限合夥負責人。
>   三、民法或其他法律規定對外代表法人之董事或理事。
>   四、商業登記法規定之商業負責人。
>   五、其他非法人團體之代表人或管理人。
> 2. 前項規定之人與實際負責業務之人不同時，以實際負責業務之人為準。

納稅義務人的身份的轉嫁的規定，而非行爲責任的轉嫁。行爲人是此等自然人，但并非具有納稅義務人之身份，（納稅義務人是法人或非法人團體）。

c.f.
什麽是身份的轉嫁，什麽是行爲責任的轉嫁？

什麽是身份的轉嫁：本來不具有納稅義務人之身份，但依據此等規定，而負擔納稅義務人所應負擔之行爲義務（誠實及時完全申報），並且對自己違反了所負擔的此等義務而承擔相應的罪責

什麽是行爲責任的轉嫁：往往體現在在法規範中是：代罰、轉嫁罰、連帶處罰（爲了別人的行爲而被處罰，這在我們的文化情境中並不陌生），此概念，違反現代法治囯的基本精神【個人罪責原則、個人歸咎原則】。一個人不爲別人的違法行爲而負責。現代法律：每一個人是自己的行爲主體。

稅捐稽徵法47條，本質上是【身份轉嫁】的規定，與現代法治國家的【個人罪責原則】無違。

#### 行爲

以詐術或其他不正當方法逃漏稅捐

實務上：僅限於積極作爲，不包含消極不作爲

以下行爲被實務上評價爲是【不作爲】，而不構成【以詐術或其他不正當方法】，僅以【漏稅罰（行政罰）】而非難：

- 不申報（應申報未申報）
- 短報（應申報已申報而短報）
- 漏報（應申報已申報而漏報）

實務上被認定為【積極作爲】之行爲，才該當【詐術或其他不正當方法】的惡性：

- 積極地僞造成本費用憑證（應申報已申報）
  - e.g. 虛增成本費用、進項稅額

以上是最高法院至今仍維持的見解。

> 請同學們想一想，哪種行爲才是最可惡的！
> 師：都一樣可惡，都一樣造成國家對於稅捐債權的無知狀態，造成稅捐收入的短漏。我們的國家是用一個很沒有意義的區別標準去衡量行爲的可非難性。

e.g.短報，實質上是一整個的虛僞不實的申報行爲。在此跟虛增成本費用沒有本質上的區別。

如果要在惡性上做區別，惡性最高的應該是【應申報未申報】，反而不構成逃漏稅捐罪。在實務上僅僅以【商業會計法71條，財務報表不實】去評價。

不是法律的問題，是最高法院的司法審理，判例和決議，將【以詐術或其他不正當方法】，限於【積極作爲】。

c.f.
商業會計法和稅捐稽徵法，所保護的法益是不同領域的。

- 商業會計法：財報的真實性，真實呈現營利事業的財務狀況，保護投資人：股東、債權人，保護的是私法法益。 
- 稅捐稽徵法：保護的是國家的稅捐債權的完整性、及時性。

國家的稅捐債權，不應該變成用商業會計法來保護！

不當的司法實務限縮了稅捐稽徵法41條的規定。

但其條文本身的法律文字也是不夠精確的：【以詐術或其他不正當方法】：【事實（課稅、免稅）的隱匿，或作虛僞不實的申報】應包括積極作爲、消極不作爲。



#### 結果

【以詐術或其他不正當方法逃漏稅捐者】，并未强調【導致逃漏稅捐】之結果，但司法實務上，需要有【逃漏稅捐的實害結果】作爲構成要件。

在理論上，是一個結果犯的概念。

是否要有這個結果的要件？以【實害結果（現行實務）】或【危險】作爲結果的？

若客觀上不構成會有短漏稅款之危險者，不構成逃漏稅捐罪。

- 以【實害結果（現行實務）】：要實際計算實害結果（逃漏稅捐）的數額，營業稅比較不好算，要勾稽，看遞回地看前n手的，難以對賬。
- 以【危險】，則不必計算實害之具體數額，是以【足生國家產生短漏稅捐之危險】作爲結果，即【危險犯】。采用營業稅的國家，往往采此説（德國）。




#### 主觀構成要件

> 刑法第12條
> 
> 第 12 條
> 行為非出於故意或過失者，不罰。
> 過失行為之處罰，以有特別規定者，為限。


### 漏稅罰（行政罰）

我國現狀，稅捐制裁以漏稅罰為中心。
僅僅金錢罰，沒有自由罰，除非拘提管收。

數額微小者，可能是過失，但補稅+裁罰1倍，對於過失者，依然是過重！

漏稅罰包含故意及過失，對於過失者，可能會有情輕罰重。

漏稅罰對於故意、惡性重大的行爲義務人，制裁效果甚微。人家早就脫產了

應該要責罰相當：故意、惡性重大（未申報、短漏報、虛增成本費用）

漏報，要依個別情形判斷：

- 可能會出現過失漏報（考慮漏報與收入之比例）：可能收入100萬，但漏報100快，比較可能是過失的，惡性輕微，應該罪責相當。
- 可能收入100萬，但漏報業外收入10000萬，比較可能是故意的，惡性重大，應以【逃漏稅捐罪】加以制裁。

德國：故意：逃漏稅捐罪

## 稅捐救濟法

【復】查-訴願-訴訟

- 【復】查-訴願：行政自我審查的行政救濟程序
- 訴訟：司法救濟程序
稅捐法部門自己創設的訴願前置程序：【復查】

凡是算錢的（核課、裁罰），全都要回到原處分機關，【復查】作爲訴願前置程序。撤銷訴願、行政訴訟之前要有【復查】程序

行政法院的體系，今年0805起：三級二審

- 高行地行（簡易，訴訟標的金額50萬）
- 高行
- 最高行

中高行：巡迴法庭（for苗慄、南投...）


不涉及到算錢的救濟，就不要先 ~~【復查】~~：
非以金錢為内容的（人的、物的保全、分期繳納被拒絕...期限利益被取消、實物抵繳被否准、溢繳稅款之返還被拒絕、）：訴願-訴訟，沒有復查的訴願前置程序。以特定行爲義務為内容，【課予義務之訴願、訴訟；一般給付訴訟（行政機關調走賬簿不還）】

還有其他種類的而訴訟類型，

行政處分無效或不成立之訴，是其他訴訟類型都不符合時才會用。


---
原處分、復查處分、訴願處分

實務上：進入訴訟程序，以上三者都構成行政訴訟的程序標的，寫訴狀的時候，3個都要寫

